/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Wendy.H.L (https://sketchfab.com/Wendy.H.L)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cosmetic-cream-jar-1986b983e79f4c6892e4adc8a91db4f2
Title: Cosmetic Cream Jar
*/

import React from 'react'
import { useGLTF, Decal, useTexture } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Jar_Plastic-jar_0']: THREE.Mesh
    Cream_Contents_0: THREE.Mesh
    ['Lid001_Plastic-lid_0']: THREE.Mesh
  }
  materials: {
    ['Plastic-jar']: THREE.MeshStandardMaterial
    Contents: THREE.MeshStandardMaterial
    ['Plastic-lid']: THREE.MeshStandardMaterial
  }
}

interface CreamModelProps extends React.ComponentPropsWithoutRef<'group'> {
  jarColor?: string
  lidColor?: string
  contentsColor?: string
}

export default function CreamModel({
  jarColor = '#BD663B',
  lidColor = '#E7D9BE',
  contentsColor = '#E3C295',
  ...props
}: CreamModelProps) {
  const { nodes, materials } = useGLTF('/models/cosmetic_cream_jar.glb') as unknown as GLTFResult
  const texture = useTexture('/images/label.png')

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0.23, 59.331, -0.014]} rotation={[-Math.PI / 2, 0, -2.121]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Jar_Plastic-jar_0'].geometry}
            material={materials['Plastic-jar']}
          >
            <meshStandardMaterial color={jarColor} roughness={0.3} metalness={0.2} />
            <Decal
              position={[1, -0.3, -0.1]}
              rotation={[Math.PI / 2, Math.PI / 2, 0]}
              scale={[1, 1, 1]}
            >
              <meshBasicMaterial map={texture} transparent />
            </Decal>
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cream_Contents_0.geometry}
            material={materials.Contents}
            position={[0.001, -0.002, 0.302]}
            rotation={[0, 0, 2.893]}
            scale={0.993}
          >
            <meshStandardMaterial color={contentsColor} />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Lid001_Plastic-lid_0'].geometry}
            material={materials['Plastic-lid']}
            position={[-1.128, 0.589, 0.221]}
            rotation={[-0.233, -0.853, 2.836]}
          >
            <meshStandardMaterial color={lidColor} />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/cosmetic_cream_jar.glb')
useTexture.preload('/images/label.png')
